services:
  postgres_db:
    image: postgres:14
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: Kevinsex250806@
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    volumes:
      - canchaya_data:/var/lib/postgresql/data
    networks:
      - canchaya_network

  backend:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres_db
      - DB_PORT=5432
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=Kevinsex250806@
    depends_on:
      - postgres_db
    networks:
      - canchaya_network

volumes:
  canchaya_data:

networks:
  canchaya_network:
