server:
  port: 8080
  # servlet:
  #   context-path: /api/v1

spring:
  application:
    name: canchaYa
  datasource:
    url: jdbc:postgresql://localhost:5432/canchaya
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  security:
    oauth2:
      resourceserver:
        jwt:
          # Temporary issuer-uri for testing, will need real Cognito User Pool URL later
          issuer-uri: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_idLO2Of02